package-lock.json
package.json
src/Pages/AccountDetails.js
src/styles/Contents.css

JIRA: https://champlainsaintlambert.atlassian.net/browse/CWCP-37
Context:
This ticket contains the frontend for the delete account for registered user.
Changes
- AccountDetails
- Contents.css
If this is a change to the UI, include before and after screenshots to show the differences.
If this is a new UI feature, include screenshots to show reviewers what it looks like.
Before:
There's the account "minseok123@email.com" 
After:
After deleting the account, goes on Homepage with logout
The account is deleted

feat/(CWCP-37): Delete Account

---

package-lock.json
package.json
src/App.css
src/App.js
src/Components/SiteHeader.js
src/Pages/AccountDetails.js
src/Pages/ProductDetails.js

JIRA: https://champlainsaintlambert.atlassian.net/browse/CWCP-29
Context:
This ticket is to allow the user to add products to their shopping cart, regardless of if they're logged-in or not.
Changes
- Added sessionId for guest users in App.js
- AddToCart and GetAvailable quantity methods in ProductDetails.js
- Popup when product succcessfully added in ProductDetails.js
Before:
After:
Can pick how many items to add: 
Maxes out at the available quantity (and doesn't go below 0):

Feat(CWCP-29): Add Item to Cart

---

src/Auth/AuthService.js
src/Components/Constants.js
src/Components/SiteHeader.js
src/Pages/AccountDetails.js
src/Pages/AddEmployee.js
src/Pages/AdminPanel.js
src/Pages/AdminProductDetails.js
src/Pages/Categories.js
src/Pages/EditEmployee.js
src/Pages/Employees.js
src/Pages/Inventory.js
src/Pages/InventoryDetails.js
src/Pages/ProductDetails.js
src/Pages/Products.js
src/Pages/ShoppingCart.js
src/Pages/SupplierDetails.js
src/Pages/Suppliers.js

This ticket is about is about updating the API calls to use the hosted backed
- All files with an API call to the backed
- Constants.js

Conf(CWCP): Update api calls

---

src/App.js
src/Components/Constants.js
src/Pages/EditAccount.js
src/styles/Contents.css

JIRA: link to jira ticket
https://champlainsaintlambert.atlassian.net/browse/CWCP-36
Context:
What is the ticket about and why are we doing this change.
This ticket is about being able to edit their account information as a user (just the name).
Changes
What are the various changes and what other modules do those changes effect.
This can be bullet point or sentence format.
- Account details
- Contents.css
- Edit Account added
- Added route in App.js
UI Changes
Before:
After:

Feat(CWCP-36): Edit account details

---

package-lock.json
src/Components/SiteHeader.js
src/Pages/Categories.js
src/Pages/HomePage.js
src/Pages/Products.js

JIRA: https://champlainsaintlambert.atlassian.net/browse/CWCP-78
Context:
This ticket is to allow the fix the search products feature. Now, the category Id is taken into account when searching for something after selecting a specific category. Before, it would show all the products matching the search query, but now the results depend on if a category is selected before the search.
Changes
- siteHeader
- categories
- homepage
- products
UI Changes after:
(when you search product in a different category than you are currently in, it does not show)
Searching for empty string gives you an error:

Bug(CWCP-78): Fix search products FE

---

src/Pages/AdminProductDetails.js
src/Pages/EditProductForm.js

Fix update product details and add/delete compatible car

Fixed update and add/delete car

---

package-lock.json
package.json
src/Pages/Orders.js

JIRA: https://champlainsaintlambert.atlassian.net/browse/CWCP-40
This ticket is to allow the admin/order employees to view the orders placed by the customers.
- orders.js

Feat(CWCP-40): View orders

---

src/App.css
src/Pages/ShoppingCart.js

JIRA: https://champlainsaintlambert.atlassian.net/browse/CWCP-31
Context:
This ticket is to allow the user to be able to update the quantity of an item in the shopping cart so that user can checkout more than one of a product. In addition, when the item quantity hits the zero, it asks the user whether to keep item in the cart or not.
Changes
• App.css
• ShoppingCart.js
Before:
After:

feat/(CWCP-31): Update Item Quantity

---

src/App.css
src/Pages/AdminProductDetails.js
src/Pages/EditProductForm.js
src/Pages/ProductDetails.js
src/Pages/Products.js

JIRA: https://champlainsaintlambert.atlassian.net/browse/CWCP-87
Context:
This ticket is to allow the customers to see different pictures of the products as well as allow the admin to upload pictures to a product.
Changes
- Products 
- ProductDetails carousel
- AdminProducts
- EditProductForm carousel and upload
Before:
After:
After uploading the image, the input is cleared and a success message appears

Feat(CWCP-87): Hosted Images

---

src/App.css
src/Pages/OrderDetails.js

https://champlainsaintlambert.atlassian.net/browse/CWCP-74
What is the ticket about and why are we doing this change.
This ticket is about being able, as an admin, to stop the processing of an order by setting the status to cancelled when a customer calls to cancel an order.
What are the various changes and what other modules do those changes effect.
This can be bullet point or sentence format.
- "Cancel order" button added to the order details page
- Button is only enable when status is "PLACED"
- Message displayed when cancellation is successful

Feat/CWCP-74 Cancel Order

---

src/App.js
src/Components/SiteHeader.js
src/Pages/AccountDetails.js
src/Pages/AccountManagement.js
src/Pages/AddressPage.js
src/styles/Contents.css

JIRA: https://champlainsaintlambert.atlassian.net/browse/CWCP-39
Context:
This ticket is to allow the user to be able to add a shipping address to their account so that user don’t need to re-enter the shipping address.
Changes
- App.js
- SideHeader.js
- AccountDetails.js
- AccountManagement.js (Created)
- AddressPage.as 
- Contents.css
Before:
After: 
When User don't have address:
Error Message when it's submitted with empty field:
Submitted Correctly:
Edit Address:

feat/(CWCP-39): Add Shipping Address

---

src/App.css
src/Components/SideBar_admin.js
src/Components/SiteHeader.js
src/Pages/AdminProductDetails.js
src/Pages/Checkout.js
src/Pages/EditProductForm.js
src/Pages/HomePage.js
src/Pages/InventoryDetails.js
src/Pages/ProductDetails.js
src/Pages/ShoppingCart.js
src/styles/Contents.css
src/styles/Sidebar.css

https://champlainsaintlambert.atlassian.net/browse/CWCP-88
What is the ticket about and why are we doing this change.
This ticket is about making the website responsive so that it can be properly viewed on a smaller screen (for phones). It is also about improving the UI in terms of layout without changing the design from Figma.
What are the various changes and what other modules do those changes effect.
This can be bullet point or sentence format.
- Added hamburger menu for admin panel when viewed on phone
- Responsive site header and forms
- Made UI consistent

Feat/CWCP-88 Responsive UI and Improved UI

---

package-lock.json
package.json
src/App.js
src/Components/Constants.js
src/Pages/Checkout.js

https://champlainsaintlambert.atlassian.net/browse/CWCP-83
This ticket is about allowing a customer to enter their billing information so that they can purchase their order.
- Checkout.js
In both production and testing environments, the payment is done with a test credit card and doesn't charge any real money

Feat(CWCP-83): Implement payment

---

src/App.css
src/App.js
src/Auth/AuthService.js
src/Pages/Checkout.js
src/Pages/OrderDetails.js
src/Pages/Orders.js

JIRA: link to jira ticket
https://champlainsaintlambert.atlassian.net/browse/CWCP-43
Context:
This ticket is about allowing the admin to set the order as shipped and provide the necessary details to also send an email to the customer
Changes
- Orders.js
- OrderDetails.js
- App.css
UI CHANGES
After

Feat(CWCP-43): Ship order

---

src/Components/Constants.js
src/Pages/Checkout.js

https://champlainsaintlambert.atlassian.net/browse/CWCP-62
What is the ticket about and why are we doing this change.
This ticket is about allowing a registered user to auto filll the shipping information in the checkout form with his account's pre-saved information (shipping address and account details). A guest user will not see this option when checking out.
What are the various changes and what other modules do those changes effect.
This can be bullet point or sentence format.
- Added button "Use Account Details"
- Button is only enabled when user is authenticated

feat/CWCP-62 Autofill Shipping

---

src/App.js
src/Components/Constants.js
src/Pages/AccountDetails.js
src/Pages/AccountManagement.js
src/Pages/OrderHistory.js
src/Pages/ShoppingCart.js
src/styles/Contents.css

JIRA: link to jira ticket
https://champlainsaintlambert.atlassian.net/browse/CWCP-92
Context:
This ticket is about allowing the customer to view their order history as well as the status of their order and shipping details when it is available
Changes:
- AccountDetails
- AccountManagement
- OrderHistory
- Contents.css

feat(CWCP_92): order status and cancel order

---

src/Pages/Products.js

Changes:
Products.js
Before:
it didn't work 
After: 
when there's no matching:
when there's matching:

Bug fix additional filters on frontend

---

src/App.css
src/App.js
src/Components/Constants.js
src/Components/SiteFooter.js
src/Components/SiteHeader.js
src/Pages/AboutUs.js
src/Pages/AccountManagement.js
src/Pages/Checkout.js
src/Pages/HomePage.js

JIRA: link to jira ticket
https://champlainsaintlambert.atlassian.net/browse/CWCP-91
Context:
This ticket is about allowing the customer's to be able to seek help by calling the provided number (currently a placeholder) or sending an email
Changes:
- AboutUs.js
- App.js
- App.css
UI Changes:
After

Feat(CWCP-91): Contact us

---

public/index.html
src/Components/Constants.js
src/Components/SiteHeader.js
src/Pages/OrderHistory.js
src/styles/Contents.css

used google translate and it finally works

feat(CWCP_93): improved translation

---

src/App.css
src/Components/SiteFooter.js
src/Pages/AccountManagement.js
src/Pages/AddressPage.js
src/Pages/Categories.js
src/Pages/Checkout.js
src/Pages/Inventory.js
src/Pages/InventoryReport.js
src/Pages/OrderHistory.js
src/Pages/ProductSalesReport.js
src/Pages/Products.js
src/Pages/ShoppingCart.js
src/Pages/UserOrder.js

feat(CWCP): CSS adjustments
